{{- if .Values.global.auxiliaryServices.docs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app: docs
    {{- include "wds-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.auxiliaryServices.docs.deploymentExtraLabelsOverride | default .Values.global.deploymentExtraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.auxiliaryServices.docs.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: docs
      {{- include "wds-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: docs
        {{- include "wds-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: docs
          image: "{{ .Values.global.registry }}/webdatasource/docs:{{ .Values.auxiliaryServices.docs.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.auxiliaryServices.docs.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.auxiliaryServices.docs.resourcesOverride | default .Values.global.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      nodeSelector:
        {{- with .Values.auxiliaryServices.docs.nodeSelectorOverride | default .Values.global.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      tolerations:
        {{- with .Values.auxiliaryServices.docs.tolerationsOverride | default .Values.global.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      affinity:
        {{- with .Values.auxiliaryServices.docs.affinityOverride | default .Values.global.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}