{{- if and .Values.global.auxiliaryServices.playground.enabled (.Values.global.hpa) }}
  {{- $name := "playground" }}
  {{- $global := (default (dict) .Values.global.hpa) }}
  {{- $service := (default (dict) .Values.auxiliaryServices.playground.hpa) }}
  {{- $serviceHasEnabled := hasKey $service "enabled" }}
  {{- $enabled := ternary ($service.enabled) ($global.enabled) $serviceHasEnabled }}
  {{- if $enabled }}
    {{- $min := (default $global.minReplicas $service.minReplicas) }}
    {{- $max := (default $global.maxReplicas $service.maxReplicas) }}
    {{- $cpu := (default $global.targetCPUUtilizationPercentage $service.targetCPUUtilizationPercentage) }}
    {{- $mem := (default $global.targetMemoryUtilizationPercentage $service.targetMemoryUtilizationPercentage) }}
    {{ include "wds-helm-chart.hpa" (dict
        "ctx" .
        "name" $name
        "minReplicas" $min
        "maxReplicas" $max
        "cpu" $cpu
        "memory" $mem
      ) }}
  {{- end }}
{{- end }}
