{{- if .Values.global.auxiliaryServices.docs.enabled }}
  {{ include "wds-helm-chart.deployment" (dict 
    "ctx" . 
    "name" "docs" 
    "labels" (merge (default (dict) .Values.auxiliaryServices.docs.deploymentExtraLabelsOverride) (default (dict) .Values.global.deploymentExtraLabels)) 
    "replicas" (.Values.auxiliaryServices.docs.replicaCount | default 1)
    "nodeSelector" (.Values.auxiliaryServices.docs.nodeSelectorOverride | default .Values.global.nodeSelector)
    "tolerations" (.Values.auxiliaryServices.docs.tolerationsOverride | default .Values.global.tolerations)
    "affinity" (.Values.auxiliaryServices.docs.affinityOverride | default .Values.global.affinity)
      "containers" (list
        (dict
          "name" "docs"
          "registry" .Values.global.registry
          "image" (.Values.auxiliaryServices.docs.image.name | default "webdatasource/docs")
          "tag" (.Values.auxiliaryServices.docs.image.tag | default .Chart.AppVersion)
          "imagePullPolicy" (.Values.auxiliaryServices.docs.image.pullPolicy)
          "env" (list (dict "name" "BASE_PATH" "value" (print .Values.global.ingress.basePath "docs")))
          "ports" (list (dict "name" "http" "containerPort" 80))
          "livenessProbePath" (print .Values.global.ingress.basePath "docs/health")
          "livenessProbePort" 80
          "readinessProbePath" (print .Values.global.ingress.basePath "docs/health")
          "readinessProbePort" 80
        )
      )
  ) }}
{{- end }}