{{- if .Values.global.auxiliaryServices.playground.enabled }}
  {{- $name := "playground" }}
  {{- $params := include "dictAddMissing" (list .Values.auxiliaryServices.playground.pdb .Values.global.pdb) | fromYaml -}}
  {{- if $params.enabled }}
    {{ include "wds-helm-chart.pdb" (dict
        "ctx" .
        "name" $name
        "minAvailable" $params.minAvailable
        "maxUnavailable" $params.maxUnavailable
      ) }}
  {{- end }}
{{- end }}
