{{- if eq .Values.global.coreServices.mode "MultiService" }}
  {{- $name := "dapi" }}
  {{- $env := list
    (dict "name" "DATAKEEPER_ORIGIN" "value" "http://datakeeper")
    (dict "name" "SCRAPER_ORIGIN" "value" "http://scraper")
    (dict "name" "IDEALER_ORIGIN" "value" "http://idealer")
    (dict "name" "JOB_TYPES" "value" (join "," .Values.global.coreServices.jobTypes))
    (dict "name" "MIN_LOG_LEVEL" "value" .Values.global.minLogLevel)
    (dict "name" "BASE_PATH" "value" .Values.global.ingress.basePath)
  }}

  {{- if .Values.global.coreServices.license.key }}
    {{- $env = append $env (dict "name" "LICENSE_KEY" "value" .Values.global.coreServices.license.key) }}
  {{- else if .Values.global.coreServices.license.keyRef }}
    {{- $env = append $env (dict "name" "LICENSE_KEY" "valueFrom" (dict "secretKeyRef" (dict "name" .Values.global.coreServices.license.keyRef.name "key" .Values.global.coreServices.license.keyRef.key))) }}
  {{- else }}
    {{- fail "Either coreServices.license.key or coreServices.license.keyRef must be set when coreServices.mode is MultiService" }}
  {{- end }}
  
  {{- if .Values.global.coreServices.databases.mongodb.connectionString }}
    {{- $env = append $env (dict "name" "MONGODB_CONNECTION_STRING" "value" .Values.global.coreServices.databases.mongodb.connectionString ) }}
  {{- else if .Values.global.coreServices.databases.mongodb.connectionStringSecretRef }}
    {{- $env = append $env (dict "name" "MONGODB_CONNECTION_STRING" "valueFrom" (dict "secretKeyRef" (dict "name" .Values.global.coreServices.databases.mongodb.connectionStringSecretRef.name "key" .Values.global.coreServices.databases.mongodb.connectionStringSecretRef.key))) }}
  {{- else }}
    {{- fail "Either coreServices.databases.mongodb.connectionString or coreServices.databases.mongodb.connectionStringSecretRef must be set when coreServices.mode is MultiService" }}
  {{- end }}

  {{- if .Values.global.coreServices.databases.mongodb.databaseName }}
    {{- $env = append $env (dict "name" "MONGODB_DATABASE_NAME" "value" (.Values.coreServices.dapi.databases.mongodb.databaseName | default .Values.global.coreServices.databases.mongodb.databaseName)) }}
  {{- end }}

  {{- if .Values.global.coreServices.exceptionResponseDelayMs }}
    {{- $env = append $env (dict "name" "GLOBAL_EXCEPTION_RESPONSE_DELAY_MS" "value" .Values.global.coreServices.exceptionResponseDelayMs) }}
  {{- end }}

  {{ include "wds-helm-chart.deployment" (dict
    "ctx" .
    "name" $name
    "labels" (merge (default (dict) .Values.coreServices.dapi.deploymentExtraLabelsOverride) (default (dict) .Values.global.deploymentExtraLabels))
    "replicas" (.Values.coreServices.dapi.replicaCount | default 2)
    "nodeSelector" (.Values.coreServices.dapi.nodeSelectorOverride | default .Values.global.nodeSelector)
    "tolerations" (.Values.coreServices.dapi.tolerationsOverride | default .Values.global.tolerations)
    "affinity" (.Values.coreServices.dapi.affinityOverride | default .Values.global.affinity)
    "containers" (list
      (dict
        "name" "dapi"
        "registry" .Values.global.registry
        "image" (.Values.coreServices.dapi.image.name | default "webdatasource/dapi")
        "tag" (.Values.coreServices.dapi.image.tag | default .Chart.AppVersion)
        "imagePullPolicy" (.Values.coreServices.dapi.image.pullPolicy | default "IfNotPresent")
        "ports" (list (dict "name" "http" "containerPort" 8080))
        "env" $env
      )
    )
  ) }}
{{- end }}
