{{- if eq .Values.global.coreServices.mode "MultiService" }}
apiVersion: v1
kind: Service
metadata:
  name: scraper
  labels:
    app: scraper
    {{- include "wds-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.coreServices.scraper.serviceExtraLabelsOverride | default .Values.global.serviceExtraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  ports:
    - name: grpc-web
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: scraper
    {{- include "wds-helm-chart.selectorLabels" . | nindent 4 }}
{{- end }}
