{{- if eq .Values.global.coreServices.mode "MultiService" }}
  {{- $name := "scraper" }}
  {{ include "wds-helm-chart.deployment" (dict
    "ctx" .
    "name" $name
    "labels" (merge (default (dict) .Values.coreServices.scraper.deploymentExtraLabelsOverride) (default (dict) .Values.global.deploymentExtraLabels))
    "replicas" (.Values.coreServices.scraper.replicaCount | default 2)
    "nodeSelector" (.Values.coreServices.scraper.nodeSelectorOverride | default .Values.global.nodeSelector)
    "tolerations" (.Values.coreServices.scraper.tolerationsOverride | default .Values.global.tolerations)
    "affinity" (.Values.coreServices.scraper.affinityOverride | default .Values.global.affinity)
    "containers" (list
      (dict
        "name" "scraper"
        "registry" .Values.global.registry
        "image" (.Values.coreServices.scraper.image.name | default "webdatasource/scraper")
        "tag" (.Values.coreServices.scraper.image.tag | default .Chart.AppVersion)
        "imagePullPolicy" (.Values.coreServices.scraper.image.pullPolicy | default "IfNotPresent")
        "ports" (list (dict "name" "grpc-web" "containerPort" 8082))
        "env" (list
          (dict "name" "LICENSE_KEY" "value" .Values.global.coreServices.license.key)
          (dict "name" "MIN_LOG_LEVEL" "value" .Values.global.minLogLevel)
        )
      )
    )
  ) }}
{{- end }}
