{{- if eq .Values.global.coreServices.mode "MultiService" }}
  {{- $name := "scraper" }}
  {{- $global := (default (dict) .Values.global.pdb) }}
  {{- $service := (default (dict) .Values.coreServices.scraper.pdb) }}
  {{- $serviceHasEnabled := hasKey $service "enabled" }}
  {{- $enabled := ternary ($service.enabled) ($global.enabled) $serviceHasEnabled }}
  {{- if $enabled }}
    {{- $min := (default $global.minAvailable $service.minAvailable) }}
    {{- $max := (default $global.maxUnavailable $service.maxUnavailable) }}
    {{ include "wds-helm-chart.pdb" (dict
        "ctx" .
        "name" $name
        "minAvailable" $min
        "maxUnavailable" $max
      ) }}
  {{- end }}
{{- end }}
