{{- if and (eq .Values.global.coreServices.mode "MultiService") .Values.global.coreServices.search.enabled }}
  {{- $name := "retriever" }}
  {{- $params := include "dictAddMissing" (list .Values.coreServices.retriever.pdb .Values.global.pdb) | fromYaml -}}
  {{- if $params.enabled }}
    {{ include "wds-helm-chart.pdb" (dict
        "ctx" .
        "name" $name
        "minAvailable" $params.minAvailable
        "maxUnavailable" $params.maxUnavailable
      ) }}
  {{- end }}
{{- end }}

