{{- if eq .Values.global.coreServices.mode "MultiService" }}
  {{- $name := "idealer" }}
  {{- $env := list
    (dict "name" "DB_CONNECTION_STRING" "value" .Values.global.coreServices.databases.mongodb.connectionString)
    (dict "name" "LICENSE_KEY" "value" .Values.global.coreServices.license.key)
    (dict "name" "MIN_LOG_LEVEL" "value" .Values.global.minLogLevel)
  }}

  {{ include "wds-helm-chart.deployment" (dict
    "ctx" .
    "name" $name
    "labels" (merge (default (dict) .Values.coreServices.idealer.deploymentExtraLabelsOverride) (default (dict) .Values.global.deploymentExtraLabels))
    "replicas" (.Values.coreServices.idealer.replicaCount | default 2)
    "nodeSelector" (.Values.coreServices.idealer.nodeSelectorOverride | default .Values.global.nodeSelector)
    "tolerations" (.Values.coreServices.idealer.tolerationsOverride | default .Values.global.tolerations)
    "affinity" (.Values.coreServices.idealer.affinityOverride | default .Values.global.affinity)
    "containers" (list
      (dict
        "name" "idealer"
        "registry" .Values.global.registry
        "image" (.Values.coreServices.idealer.image.name | default "webdatasource/idealer")
        "tag" (.Values.coreServices.idealer.image.tag | default .Chart.AppVersion)
        "imagePullPolicy" .Values.coreServices.idealer.image.pullPolicy
        "ports" (list (dict "name" "grpc-web" "containerPort" 8082))
        "env" (list
          (dict "name" "DB_CONNECTION_STRING" "value" .Values.global.coreServices.databases.mongodb.connectionString)
          (dict "name" "LICENSE_KEY" "value" .Values.global.coreServices.license.key)
          (dict "name" "MIN_LOG_LEVEL" "value" .Values.global.minLogLevel)
        )
      )
    )
  ) }}
{{- end }}
