{{- if eq .Values.global.coreServices.mode "MultiService" }}
  {{- $name := "dapi" }}
  {{- $params := include "dictAddMissing" (list .Values.coreServices.dapi.pdb .Values.global.pdb) | fromYaml -}}
  {{- if $params.enabled }}
    {{ include "wds-helm-chart.pdb" (dict
        "ctx" .
        "name" $name
        "minAvailable" $params.minAvailable
        "maxUnavailable" $params.maxUnavailable
      ) }}
  {{- end }}
{{- end }}
