{{- if eq .Values.global.coreServices.mode "MultiService" }}
apiVersion: v1
kind: Service
metadata:
  name: dapi
  labels:
    app: dapi
    {{- include "wds-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.coreServices.dapi.serviceExtraLabelsOverride | default .Values.global.serviceExtraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: dapi
    {{- include "wds-helm-chart.selectorLabels" . | nindent 4 }}
{{- end }}
